package com.cms.pojo;

import com.baomidou.mybatisplus.annotation.TableId;
import lombok.Data;
import java.util.Date;

@Data
public class IdCheckAllPojo {
    private String agentCode;
    private String recomAgentCode;
    private String recomAgentName;
    private String idType;
    private String idNo;
    private String sex;
    private Date birthday;
    private String marriageStatus;
    private String nationality;
    private String nativeplace;
    private String postcode;
    private String phone;
    private String email;
    private String homephone;
    private String healthStatus;
    private String outlookStatus;
    private String healthRemark;
    private String attendanceNo;
    private String graduateSchool;
    private String major;
    private String highestDegree;
    private String firstDegree;
    private String degree;
    private String degreeCode;
    private String degreeName;
    private String oldIndustryType;
    private String oldOccupation;
    private String oldCom;
    private String oldJobDuty;
    private String workAge;
    private String province;
    private String city;
    private String area;
    private String address;
    private String train;
    private String contractType;
    private Date contractStartDate;
    private Date contractEndDate;
    private String certificateNo;
    private String uniteBankNum;
    private String bankCode;
    private String bankAccount;
    private String bankProvince;
    private String bankCity;
    private String bankAddress;
    private String operator;
    private Date makeDate;
    private String makeTime;
    private Date modifyDate;
    private String modifyTime;
    private String rgtType;
    private String regAddress;
    private String sapCode;
    private String agentName;
    private String agentJob;
    private String agentGrade;
    private String agentState;
    private String branchType;
    private String manageCom;
    private String initGrade;
    private Date employDate;
    private Date signDate;
    private Date inDueFormDate;
    private Date outWorkDate;
    private Date doneDate;
    private String insertKind;
    private String agentGroup;
    private Date workDate;
    private String introduce;
    private String repeatFlag;
    private String isPeers;
}
