spring:
  datasource:
    username: edm_dat
    password: Edm_dat#123
    url: jdbc:mysql://10.219.112.153:3306/edm_dat?characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 9998
mybatis:
  type-aliases-package: com.edm.entity
  mapper-locations: classpath:mapper/*.xml
#logging:
#  level:
#    com:
#      edm:
#        mapper: debug
#日志打印
logging.config=classpath:
  logback-spring.xml
# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

